packages:
  - apps/*

catalog:
  "@mediapipe/tasks-vision": ^0.10.35
  "@pixiv/three-vrm": ^3.5.2
  "@tailwindcss/vite": ^4.2.4
  "@types/node": ^24
  "@types/three": ^0.184.0
  tailwindcss: ^4.2.4
  three: ^0.184.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
